---
title: "Academic and Professional Experiences"
output: 
  html_document:
    toc: true
    toc_float: true
---

## Education


**MPH Candidate at Columbia University Mailman School of Public Health, New York, NY**

Expected graduation date: May 2020

Department: Population and Family Health

Certificate: Public Health Research Methods 


**Bachelor of Arts, Vassar College, Poughkeepsie, NY**

Graduation date: May 2015

Major: Biochemistry

Correlate: Asian Studies 


## Professional Experiences


**Graduate Teaching Assistant, Mailman School of Public Health, New York, NY**


_May 2019 - Present_


  * Hold office hours to help students understand key concepts of service-based 
    quantitative data analysis

  * Assist professor with editing class handouts 

  * Grade students' homework assignments


**Research Intern, New York Presbyterian Morgan Stanley Children’s Hospital, New York, NY**	


_May 2019 – Aug 2019_


  * Recruited adolescent patients, ages 13-24, in the Pediatric Emergency 
    Department to participate in Dr. Lauren S. Chernick and Dr. Ian D. Aronson’s     “Mobile Augmented Screening Tool to Increase Adolescent Testing and Linkage 
    to Care” study. 
    
  * Created SPSS database to store baseline and follow-up data for respondents       in the Dr. Erica study. 
    
  * Compiled list of birth control methods prescribed in the Emergency   
    Department, using the National Hospital Ambulatory Medical Care Survey  
    (NHAMCS) dataset, for a data analysis plan. 
    
  * Conducted a literature search on adolescent confidentiality in the Emergency     Department.   
  
  
**Research Assistant, Guttmacher Institute, New York, NY**


_October 2016 - Present_


  * Conduct literature review on global and national incidence of abortion and 
    unintended pregnancy, global fecundity and frequency of sexual activity

  * Gather and manage abortion data from official statistics and surveys

  * Field surveys at clinics that provide publicly funded family planning 
    services to see how the recent changes in policies affect people's access to     care 


**Organic Chemistry Lab Assistant, Vassar College, New York, NY**


_September 2013 - May 2015_


  * Assist students in setting up their laboratory equipment

  * Answer questions and explain key concepts to students 


## Publications

Rossi M, Caruso F, **Kwok L**, Lee G, Caruso A, et al. (2017) [Protection by extra virgin olive oil against oxidative stress in vitro and in vivo. Chemical and biological studies on the health benefits due to a major component of the Mediterranean diet.](https://doi.org/10.1371/journal.pone.0189341) PLoS ONE 12(12): e0189341.

## COMMUNITY AND LEADERSHIP

**Volunteer, Karen Leung Foundation, Central, Hong Kong**


_Sept 2015–July 2016_


  * Registered over 700 female students, aged 9–14 years old, for the free   
    school-based HPV vaccination program at 12 primary and secondary schools in     collaboration with the Chinese University of Hong Kong. 

**Co-President of Fundraising & Development, Vassar Haiti Project, Poughkeepsie, NY**


_Aug 2014–May 2015_


  * Led team of four students in student leadership development, alumnae   
    networking, outreach, event planning, and social media maintenance. 

