---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)

data(rest_inspec)
```

## Problem 2

Column {.sidebar}
-----------------------------------------------------------------------
The following charts use data collected from restaurant inspections conducted by the New York City Department of Health and Mental Hygiene. These inspections are conducted annually to ensure that restaurants are in compliance with policies on food handling, food temperature, personal hygiene of restaurant staff and vermin control. 

This dashboard focuses on restaurants located in Brooklyn with the first chart looking at the distribution of grades aross all types of cuisine. The second chart looks at the number of critical flags by type of cuisine and the third chart looks at the distribution of health inspection scores among sweets-related restaurants. 

Column {data-width=900}
-----------------------------------------------------------------------

### Chart A

```{r}
rest_inspec %>%
  filter(.data = ., boro != "Missing") %>%
  mutate(.data = ., 
         as.factor(grade),
         fct_reorder(boro, grade)) %>%
  group_by(boro) %>%
  count(grade) %>%
  filter(.data = ., n != "NA") %>%
  plot_ly(x = ~reorder(grade, -n), y = ~n, color = ~boro, type = "bar")
```

Column {data-width=750}
-----------------------------------------------------------------------
### Number of critical flags by cuisine type in Brooklyn, New York

```{r}
rest_inspec %>%
  filter(.data = ., critical_flag == "Critical", boro == "BROOKLYN") %>%
  group_by(boro, cuisine_description) %>%
  select(.data = ., boro, critical_flag, cuisine_description) %>%
  count(critical_flag) %>%
  arrange(desc(n)) %>%
  filter(.data = ., n > 1000) %>%
  plot_ly(x = ~reorder(cuisine_description, -n), y = ~n, type = "bar") %>%
  layout(xaxis = list(title = "Type of Cuisine",
         yaxis = list(title = "Number of critical flags")))             
```

### Distribution of health inspection scores among sweets-related restaurants in Brooklyn 

```{r}
rest_inspec %>%
  filter(.data = ., boro == "BROOKLYN", score != "NA", cuisine_description == "Donuts" | cuisine_description == "Bakery" | cuisine_description == "Ice Cream, Gelato, Yogurt, Ices" | cuisine_description == "Pancakes/Waffles") %>%
  select(.data = ., boro, cuisine_description, score) %>%
  group_by(cuisine_description) %>%
  plot_ly(x = ~cuisine_description, y = ~score, type = "box", color = ~cuisine_description)
```
